app/routes.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, session, flash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from bson.objectid import ObjectId
from .db import get_db
import base64
from datetime import datetime
import urllib.parse

bp = Blueprint('main', __name__)

auth  = Blueprint('auth', __name__)

db = get_db()
user_collection = db.users
item_collection = db.items
rate_collection = db.rates
review_collection = db.reviews

@bp.route('/')
def index():

    all_items = item_collection.find()

    return render_template('list.html', items = all_items )

@bp.route('/login', methods = ['POST', 'GET'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        error = None
            
        if username is None or password is None:

            error = "Provide credentials"

            flash(error)

        user_data = user_collection.find_one({"username":username})

        if user_data is not None and check_password_hash(user_data['password'], password):

            session['username'] = username
            session['user_id'] = str(user_data['_id'])
            session['admin'] = False

            if user_data.get('admin'):
                session['admin'] = True

            return redirect(url_for('main.index'))

        else:
            print("check failed")
            error = 'Invalid username or password'
        
        flash(error)
    
    return render_template('login.html')

@bp.route('/logout')
def logout():
    session.clear()
    session.pop('admin', None)
    session.pop('username', None)
    session.pop('user_id', None)
    return redirect(url_for('main.index'))


@bp.route('/admin-panel')
def admin_panel():
    is_admin = session.get('admin') 
    if is_admin != True:
        return  redirect(url_for('main.index'))

    all_users = user_collection.find()
    all_items = item_collection.find()

    return render_template('admin_panel.html', users = all_users, items = all_items)

@bp.route('/register', methods = ['POST'])
def register():
    if request.method != 'POST':
        return render_template('admin_panel.html')

    username = request.form['username']
    password = request.form['password']
    avg_rating = 0
    reviews = 0

    hashed_password = generate_password_hash(password)

    user_collection.insert_one({"username":username, "password":hashed_password, "avgRating":avg_rating, "reviews": reviews })

    return redirect(url_for('main.admin_panel'))

@bp.route('/delete-users', methods = ['POST'])
def delete_users():
    if request.method != 'POST':
        return render_template('admin_panel.html')
    
    selected_users = request.form.getlist('user_id')

    selected_ids = [ObjectId(id) for id in selected_users]

    result = user_collection.delete_many({'_id':{'$in': selected_ids }})

    #print(f'{result} users have been deleted!')

    rate_collection.delete_many({'user_id': {'$in': selected_users} })
    review_collection.delete_many({'user_id': {'$in': selected_users}})

    return redirect(url_for('main.admin_panel'))

@bp.route('/delete-items', methods=["POST"])
def delete_items():
    if request.method != 'POST':
        return render_template('admin_panel.html')

    selected_items = request.form.getlist('item_id')

    selected_ids = [ObjectId(id) for id in selected_items]

    result = item_collection.delete_many({'_id':{'$in': selected_ids}})

    print(f'{result} items have been deleted!')

    rate_collection.delete_many({'item_id': {'$in': selected_items} })
    review_collection.delete_many({'item_id': {'$in': selected_items}})

    return redirect(url_for('main.admin_panel'))

@bp.route('/add-item', methods = ['POST'])
def add_item():
    if request.method != 'POST':
        return render_template('admin_panel.html')

    item_name = request.form.get('item_name')
    item_price = request.form.get('item_price')
    item_description = request.form.get('description')
    item_seller = request.form.get('seller_name')
    item_photo = request.files.get('item_photo')
    item_photo_b64 = base64.b64encode(item_photo.read()).decode('utf-8')
    item_type = request.form.get('item_type')

    # <option>Vinyls</option>
    # <option>Antique Furniture</option>
    # <option>GPS Sport Watches</option>
    # <option>Running Shoes</option>

    # print(f'{item_name}')
    # print(f'{item_description}')
    # print(f'{item_seller}')
    # print(f'{item_photo_b64}')
    # print(f'{item_type}')

    if item_name == None or item_price == None or item_description == None or item_seller == None or item_photo_b64 == None or item_type == None:
        print(f'None Detected!')
        return render_template('admin_panel.html')

    if item_type == 'Vinyls':
        age = request.form.get('age')

        item_collection.insert_one(
            {"name":item_name,
            "price": item_price,
            "description":item_description,
            "seller":item_seller,
            "photo":item_photo_b64,
            "type": item_type,
            "age": age
        })

        print(f'inserted Vinyls')

    elif item_type == 'Antique Furniture':
        age = request.form.get('age')
        material = request.form.get('material')

        item_collection.insert_one(
            {"name":item_name,
            "price": item_price,
            "description":item_description,
            "seller":item_seller,
            "photo":item_photo_b64,
            "type": item_type,
            "age": age,
            "material": material,
        })
    elif item_type == 'GPS Sport Watches':
        battery_life = request.form.get('battery_life')

        item_collection.insert_one(
            {"name":item_name,
            "price": item_price,
            "description":item_description,
            "seller":item_seller,
            "photo":item_photo_b64,
            "type": item_type,
            "battery": battery_life
        })
    elif item_type == 'Running Shoes':
        size = request.form.get('size')
        material = request.form.get('material')

        item_collection.insert_one(
            {"name":item_name,
            "price": item_price,
            "description":item_description,
            "seller":item_seller,
            "photo":item_photo_b64,
            "type": item_type,
            "size": size,
            "material": material
        })
    #print(f'item_received: {item_name} {item_photo_b64}')

    return redirect(url_for('main.admin_panel'))
    
@bp.route('/item-detail', methods = ['GET'])
def item_detail():
    if request.method != 'GET' or 'username' not in session:
        return redirect(url_for('main.index'))
    
    item_id = request.args.get('item_id')

    avg_rating = 0
    aggregate_input = [
        {"$match":{"item_id": item_id}},
        {"$group": 
            {
                "_id":"$item_id",
                "average_rating": {"$avg": "$rate"}
            }
        }
    ]

    avg_rating_cursor = rate_collection.aggregate(aggregate_input)

    for rate in avg_rating_cursor:
        avg_rating = rate.get('average_rating',0)

    #print(f'AVG RATING: {avg_rating}')

    avg_rating_percent = avg_rating * 10

    detailed_item = item_collection.find_one({'_id': ObjectId(item_id)})

    reviews = review_collection.find({'item_id':item_id})

    return render_template('item_details.html', item = detailed_item, rating = avg_rating, rating_percent = avg_rating_percent, reviews = reviews)
    
@bp.route('/rate/<id>', methods = ['POST'])
def rate_item(id):
    if request.method != 'POST' or 'username' not in session:
        return redirect(url_for('main.index'))

    item_rate = int(request.form['rate'])
    user_id = session.get('user_id')

    previous_rate = rate_collection.find_one( {'user_id':user_id, 'item_id': id})

    # print(f'request for {id}')
    # print(f'Rate: {item_rate}')

    if previous_rate:
        rate_collection.update_one({'user_id': user_id, 'item_id':id }, {'$set':{'rate':item_rate }})
    else:
        rate_collection.insert_one({'user_id': user_id, 'item_id':id, 'rate': item_rate })

    return redirect(request.referrer)

@bp.route('/review/<id>', methods = ['POST'])
def review(id):
    if request.method != 'POST' or 'username' not in session:
        return redirect(url_for('main.index'))

    review = request.form.get('review')
    user_id = session.get('user_id')
    username = session.get('username')
    current_date = datetime.now()

    previous_review = review_collection.find_one({'user_id':user_id, 'item_id':id})

    if previous_review:
        review_collection.update_one({'user_id': user_id, 'item_id': id,  'username': username }, {'$set':{'review':review, 'date':current_date}})
    else:
        review_collection.insert_one({'user_id': user_id, 'item_id': id, 'review':review, 'date': current_date, 'username': username })

    #print(f'Comment: {review} for id: {id}')
    return redirect(request.referrer)

@bp.route('/profile', methods = ['GET'])
def profile():
    if request.method != 'GET' or 'username' not in session:
        return redirect(url_for('main.index'))

    username = session.get('username')
    user_id = session.get('user_id')
    avg_rating = 0

    aggregate_input = [
        {"$match":{"user_id": user_id}},
        {"$group": 
            {
                "_id":"$user_id",
                "average_rating": {"$avg": "$rate"}
            }
        }
    ]

    avg_rating_cursor = rate_collection.aggregate(aggregate_input)

    for rate in avg_rating_cursor:
        avg_rating = rate.get('average_rating',0)

    #print(f'AVG RATING: {avg_rating}')

    my_reviews = review_collection.find({'user_id':user_id})
    
    return render_template('profile.html', username = username, rating = avg_rating, reviews = my_reviews)

app/templates/admin_panel.html
{% extends 'index.html' %}

{% block header %}
  <h1>{% block title %}Admin Panel{% endblock %}</h1>
{% endblock %}

{% block content %}

<div class="container vh-100 mb-3 pb-3">
    <ul class="list-group mt-5">
        <li class="list-group-item d-flex justify-content-center" id="addItemButton">
            <button class="btn btn-link "><a class="nav-link text-secondary" > Add Item</a></button>
        </li>
        <!-- <li class="list-group-item d-flex justify-content-center" id="removeItemButton">
            <button class="btn btn-link"><a class="nav-link text-secondary" > RemoveItem</a></button>
        </li> -->
        <li class="list-group-item d-flex justify-content-center" id="addUserButton">
            <button class="btn btn-link"><a class="nav-link text-secondary" > Add User</a></button>
        </li>
        <!-- <li class="list-group-item d-flex justify-content-center" id="removeUserButton">
            <button class="btn btn-link"><a class="nav-link text-secondary" > Remove User</a></button>
        </li> -->
    </ul>

    <div class="container mt-5 pt-2">
        <h2>Remove User</h2>
        <form method="post" action="{{ url_for('main.delete_users') }}">
            {% for user in users %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="user_id" value="{{ user['_id'] }}" >
                <label class="form-check-label" for="defaultCheck1">
                    {{ user['username'] }}
                </label>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary mt-4">Delete</button>
        </form>
    </div>

    <div class="container mt-5 pt-2">
        <h2>Remove Item</h2>
        <form method="post" action="{{ url_for('main.delete_items') }}">
            {% for item in items %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="item_id" value="{{ item['_id'] }}" >
                <span style="font-weight: bold;">{{ item['name'] }}</span> - 
                <span style="opacity: 0.6;">{{ item['description'] }}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary mt-4 mb-3">Delete</button>
        </form>
    </div>
</div>


  <!-- Modal For Users -->
<div class="modal fade" id="addUserModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add User</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"> -->
                <!-- <span aria-hidden="true">&times;</span> -->
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('main.register') }}"class="border border-primary p-4  rounded border-5">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="username" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter Username">
                    
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password"  name="password" class="form-control" id="password" placeholder="Password">
                        <small id="emailHelp" class="form-text text-muted">Create User as an Administrator!</small>
                    </div>
                    <button type="submit" class="btn btn-primary mt-4">Create</button>
                </form>
                <div class="modal-footer">
                    <button id="closeAddUserModal" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal For Item -->
<div class="modal fade" id="addItemModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle2" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Item</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"> -->
                <!-- <span aria-hidden="true">&times;</span> -->
            </div>
            <div class="modal-body">
                <form method="post" action="{{ url_for('main.add_item') }}" enctype="multipart/form-data">
                    <div class="form-group p-2">
                      <label for="item_name">Item Name</label>
                      <input type="text" name="item_name" class="form-control" id="item_name" placeholder="Nike, Adidas, etc.">
                    </div>
                    <div class="form-group p-2">
                        <label for="item_name">Item Price ($)</label>
                        <input type="number" name="item_price" class="form-control" id="item_price" placeholder="5 $">
                      </div>
                    <div class="form-group p-2">
                        <label for="description">Description of the Item</label>
                        <textarea class="form-control" name="description" id="item_description" rows="3" maxlength="150"></textarea>
                    </div>
                    <div class="form-group p-2">
                        <label for="seller_name">Seller Name</label>
                        <input type="text" name="seller_name" class="form-control" id="seller_name" placeholder="Company">
                    </div>
                    <div class="form-group p-2">
                        <label for="item_photo">Example file input</label>
                        <input type="file" name="item_photo" class="form-control-file" id="item_photo">
                    </div>
                    <!-- <div class="form-group p-2">
                      <label for="item_type">Example select</label>
                      <select class="form-control" id="item_type">
                        <option>Vinyls</option>
                        <option>Antique Furniture</option>
                        <option>GPS Sport Watches</option>
                        <option>Running Shoes</option>
                      </select>
                    </div> -->
                    <div class="form-group p-2">
                      <label for="item_type">Item Type</label>
                      <select multiple class="form-control" id="item_type" name="item_type">
                        <option>Vinyls</option>
                        <option>Antique Furniture</option>
                        <option>GPS Sport Watches</option>
                        <option>Running Shoes</option>
                      </select>
                    </div>
                    <div class="form-row  row p-2">
                        <div class="form-group col-md-3">
                            <label for="battery_life">Battery (h)</label>
                            <input type="number" name="battery_life" class="form-control" id="battery_life">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="age">Age (year)</label>
                            <input type="number" name="age" class="form-control" id="age">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="size">Size (EU)</label>
                            <input type="number" name="size" class="form-control" id="size">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="material" >Material </label>
                            <input type="text" name="material" class="form-control" id="material">
                        </div>
                      </div>
                    <button type="submit" class="btn btn-primary m-2">Create</button>
                  </form>
                <div class="modal-footer">
                    <button id="closeAddItemModal" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    document.addEventListener('DOMContentLoaded', function() {

        const addUserButton = document.getElementById('addUserButton');
        const addUsermodalElement = document.getElementById('addUserModalCenter');
        const closeAddUserButton = document.getElementById('closeAddUserModal');
        

        const userModal = new bootstrap.Modal(addUsermodalElement);

        addUserButton.addEventListener('click', function() {
            userModal.show();  
        });

        closeAddUserButton.addEventListener('click', function() {
            userModal.hide();
        });

        const addItemButton = document.getElementById('addItemButton');
        const addItemmodalElement = document.getElementById('addItemModalCenter');
        const closeAddItemButton = document.getElementById('closeAddItemModal');
        

        const itemModal = new bootstrap.Modal(addItemmodalElement);

        addItemButton.addEventListener('click', function(){
            itemModal.show();
        });

        closeAddItemButton.addEventListener('click', function(){
            itemModal.hide();
        });


        const variableInputElement = document.getElementById('item_type');
        const batteryLifeInput = document.getElementById('battery_life');
        const ageInput = document.getElementById('age');
        const sizeInput = document.getElementById('size');
        const materialInput = document.getElementById('material');

        disableAll();

        function disableAll(){
            batteryLifeInput.disabled = true;
            ageInput.disabled = true;
            sizeInput.disabled = true;
            materialInput.disabled = true;
        }

        variableInputElement.addEventListener('change', function() {
            const selectedOptions = Array.from(variableInputElement.selectedOptions).map(option => option.value);
            disableAll();
            if( selectedOptions.length != 1 ){
                alert("1 Item Type is allowed!");
            }
            else{
                // alert(selectedOptions[0]); // works fine
                selectedOption = selectedOptions[0];

                if(selectedOption == "Vinyls"){
                    ageInput.disabled = false;
                }
                else if(selectedOption == "GPS Sport Watches"){
                    batteryLifeInput.disabled = false;
                }   
                else if(selectedOption == "Antique Furniture"){
                    ageInput.disabled = false;
                    materialInput.disabled = false;
                }
                else if(selectedOption == "Running Shoes"){
                    sizeInput.disabled = false;
                    materialInput.disabled = false;
                }
            }
        });
        

    });
    
</script>

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alkım Cloud HW</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon" href="https://www.metu.edu.tr/sites/all/themes/odtu/favicon.ico" type="image/vnd.microsoft.icon">
  </head>

</head>
<body>
    <nav class="navbar navbar-expand-lg p-4 bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand text-light" >E-Commerce by Alkım</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto pl-4 mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-light" aria-current="page" href=" {{ url_for('main.index')}} ">Home</a>
              </li>
              <li class="nav-item ml-2">
                <a class="nav-link text-light ml-2" href="{{url_for('main.profile')}}">My Profile</a>
              </li>
              {% if session.get('admin') %}
              <li class="nav-item">
                <a class="nav-link text-light" href="{{ url_for('main.admin_panel') }}">Admin Panel</a>
              </li>
              {% endif %}
              <!-- <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li> -->
            </ul>
            <form class="d-flex" role="search" action="{{url_for('main.search')}}" type="get">
              <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      <div class="container-fluid order-start">
        <div class="row">
          <div class="col-12 d-flex justify-content-end mt-3">
            {%if session.get('username')  %}
              <a class="nav-link text-secondary" href="{{ url_for('main.logout') }}">Log Out</a>
            {% else %}
              <a class="nav-link text-secondary" href="{{ url_for('main.login') }}">Log In</a>
            {% endif %}
          </div>
        </div>
      </div>


    {% block content %}
    
    
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

app/templates/item_details.html
{% extends 'index.html' %}

{% block header %}
  <h1>{% block title %}Item{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="d-flex flex-column align-items-center mb-5">
        <h5 class="mb-2">Rating</h5>
        <div class="progress" style="width: 80%;">
            <div class="progress-bar" role="progressbar" style="width: {{rating_percent}}%;" aria-valuenow="{{ rating }}" aria-valuemin="0" aria-valuemax="100">{{ rating }}</div>
        </div>
    </div>

    <div class="d-flex justify-content-center flex-column align-items-center text-center">

        <figure class="figure">
            <img src="data:image/png;base64,{{item['photo']}}" class="figure-img img-fluid rounded"  alt="..." style="width: 40rem; height: auto;">
            <figcaption class="figure-caption"><strong> {{item['name']}} </strong></figcaption>
        </figure>
        <p> {{item['description']}}</p>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Type: </strong> {{item['type']}} </li>
            <li class="list-group-item"><strong>Seller: </strong> {{item['seller']}}</li>
            <li class="list-group-item"><strong>Price: </strong> {{item['price']}} </li>
          </ul>
          {% if item['type']=="Running Shoes" %}
                <div class="col-sm">
                    Size: {{item['size']}} (EU)
                </div>
                <div class="col-sm">
                    Material: {{item['material']}}
                </div>
                {% endif %}

                {% if item['type']=="Antique Furniture" %}
                <div class="col-sm">
                    Age: {{item['age']}} (year)
                </div>
                <div class="col-sm">
                    Material: {{item['material']}}
                </div>
                {% endif %}

                {% if item['type']=="GPS Sport Watches" %}
                <div class="col-sm">
                    Batteri Life: {{item['battery']}} (h)
                </div>
                {% endif %}

                {% if item['type']=="Vinyls" %}
                <div class="col-sm">
                    Age: {{item['age']}} (year)
                </div>
            {% endif %}

        <h2 class="mt-5" >Reviews</h2>

        {% for review in reviews %}
            <div class="col-md-8 mx-auto mb-3">
                <div class="card">
                    <div class="card-body d-flex">
                        <div>
                            <p class="card-title mb-1"><strong>{{review['username']}} </strong> - Date: {{ review['date'].strftime('%Y-%m-%d %H:%M') }} </p>
                            <p class="card-text mt-2"> {{review['review']}} </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        
    <div class="d-flex justify-content-center" style="width: 100%;">
        <form style="width: 67%;" method="post" action="{{ url_for('main.review', id = item['_id']) }}" > 
            <div class="form-group"  >
                <label for="review">Enter Review!</label>
                <textarea name="review" class="form-control" id="review" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary mt-3" >Send</button>
        </form>

    </div>

    <form class="mt-5"  method="post" action="{{url_for('main.rate_item', id = item['_id']) }}">

        <label for="customRange2" class="form-label">Rate this item!</label>
        <input type="range" name='rate' class="form-range" min="0" max="10" id="rate">

        <button type="submit" class="btn btn-primary mt-3">Rate</button>
    </form>


{% endblock %}

app/templates/login.html
{% extends 'index.html' %}

{% block header %}
  <h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}


<div class="d-flex justify-content-center align-items-center vh-100 " >
  <form method="POST" class="border border-primary p-4  rounded border-5">
    <div class="form-group">
      <label for="username">Username</label>
      <input type="username" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter Username">
     
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password"  name="password" class="form-control" id="password" placeholder="Password">
      <small id="emailHelp" class="form-text text-muted">We'll never share your credentials with anyone else.</small>
    </div>
    <div>
      {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="text text-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
    <!-- <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div> -->
    <button type="submit" class="btn btn-primary mt-4">Log In</button>
  </form>
</div>

{% endblock %}

app/templates/profile.html
{% extends 'index.html' %}

{% block header %}
  <h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}

    <div class="" style="margin-left: 20%;">
        <h1>Hello {{ username }} !</h1>
        <h6>Rating: {{ rating }}</h6>

    </div>

    <div class="col-md-8 mx-auto mb-3 mt-5">
        <h4 class="ml-2">  My Reviews</h4>
    {% for review in reviews %}
        <div class="card m-2">
            <div class="card-body d-flex">
                <div>
                    <p class="card-title mb-1"> <strong>Date:</strong> {{ review['date'].strftime('%Y-%m-%d %H:%M') }} </p>
                    <p class="card-text mt-2"> {{review['review']}} </p>
                </div>
            </div>
        </div>  
   {% endfor %}
    </div>


{% endblock %}